### ISSUE TITLE
The .tex files

### ISSUE THREAD

**Issue by zslovedd** [KastnerRG/pp4fpgas#5]
Could you please give us a guide to use .tex files to create latest pdf file ？I have no idea about how to use them. Thank you

**Comment by stephenneuendorffer** [comment]
Generally speaking, we use MikTex/TexWorks, but any recent pdflatex version should work.  latex is like a compiler so you can start it with:
pdflatex main

Some features of latex (such as the index and bibliography) require other programs to run first:
makeindex main
bibtex main

Because of the way latex works, it may also require running all of these commands multiple times to reach the final pdf.  There are numerous good latex tutorials on the web.

**Comment by zslovedd** [comment]
Dear @stephenneuendorffer ,
    I have download both MikTex and TexWorks, but it always display "File `tikz.sty' not found."  or something else not found. I am confused about it , because I search 'tikz' at https://miktex.org/packages and there are about 80 different packages about it. How can I solve it ?
    Thanks !!!
